version: "3"
services:
  rest:
    image: rest-app
    build:
      context: .
    ports:
      - "8000:80"
  mongo:
    container_name: mongo
    image: mongo:3.4.19-jessie
    ports:
      - "27017:27017"
